// src/components/dosen/use-dummy-dosen.ts
import { Pegawai, KepangkatanRow, AnggotaKeluargaRow, RiwayatPendidikanRow, JabatanFungsionalRow, InpasingRow, JabatanStrukturalRow, PenempatanRow, KendaraanRow } from '@/types';

export const dummyPegawaiList: Pegawai[] = [
  {
    nip: '19801231 200501 1 001',
    nama: 'Budi Santoso',
    gelarDepan: 'Dr.',
    gelarBelakang: 'M.Kom.',
    jenisKelamin: 'Laki-laki',
    agama: 'Islam',
    golonganDarah: 'O',
    tempatLahir: 'Bandung',
    tanggalLahir: '31 Desember 1980',
    alamat: 'Jl. Merdeka No. 10, Bandung',
    noHandphone: '081234567890',
    nbm: 'NBM12345',
    nidn: '0123456789',
    nidk: '-',
    nuptk: '-',
    idScholar: 'scholar-123',
    idScopus: 'scopus-456',
    idShinta: 'shinta-789',
    idGaruda: 'garuda-012',
    npwp: '12.345.678.9-012.000',
    emailPribadi: 'budi@gmail.com',
    emailUniversitas: 'budi@univ.ac.id',
    nikKependudukan: '3201123456789001',
    jabatanStruktural: 'Ketua Laboratorium',
    jabatanFungsional: 'Lektor Kepala',
    dokKtp: '/dokumen/ktp_budi.pdf',
    dokNbm: '/dokumen/nbm_budi.pdf',
    dokPassport: '',
    dokBpjsKesehatan: '/dokumen/bpjs_kesehatan_budi.pdf',
    dokBpjsTenagakerja: '/dokumen/bpjs_tk_budi.pdf',
    dokSertifikasiDosen: '/dokumen/serdos_budi.pdf',
    dokNidn: '/dokumen/nidn_budi.pdf',
    imgUrl: '/img/Default-Icon.jpg',
  },
  {
    nip: '19790512 200403 1 002',
    nama: 'Siti Aminah',
    gelarDepan: '',
    gelarBelakang: 'M.T.',
    jenisKelamin: 'Perempuan',
    agama: 'Islam',
    golonganDarah: 'A',
    tempatLahir: 'Jakarta',
    tanggalLahir: '12 Mei 1979',
    alamat: 'Jl. Sudirman No. 3, Jakarta',
    noHandphone: '082233445566',
    nbm: '',
    nidn: '9876543210',
    nidk: '',
    nuptk: '',
    idScholar: '',
    idScopus: '',
    idShinta: '',
    idGaruda: '',
    npwp: '',
    emailPribadi: 'siti@gmail.com',
    emailUniversitas: 'siti@univ.ac.id',
    nikKependudukan: '3174123456789012',
    jabatanStruktural: '',
    jabatanFungsional: 'Lektor',
    dokKtp: '',
    dokNbm: '',
    dokPassport: '',
    dokBpjsKesehatan: '',
    dokBpjsTenagakerja: '',
    dokSertifikasiDosen: '',
    dokNidn: '',
    imgUrl: '/img/Default-Icon.jpg',
  },
  {
    nip: '19870607 201001 1 003',
    nama: 'Andi Pratama',
    gelarDepan: '',
    gelarBelakang: 'M.Kom.',
    jenisKelamin: 'Laki-laki',
    agama: 'Islam',
    golonganDarah: 'B',
    tempatLahir: 'Surabaya',
    tanggalLahir: '07 Juni 1987',
    alamat: 'Jl. Pahlawan No. 5, Surabaya',
    noHandphone: '085612345678',
    nbm: '',
    nidn: '1122334455',
    nidk: '',
    nuptk: '',
    idScholar: '',
    idScopus: '',
    idShinta: '',
    idGaruda: '',
    npwp: '',
    emailPribadi: 'andi@gmail.com',
    emailUniversitas: 'andi@univ.ac.id',
    nikKependudukan: '3578123456789012',
    jabatanStruktural: '',
    jabatanFungsional: 'Asisten Ahli',
    dokKtp: '',
    dokNbm: '',
    dokPassport: '',
    dokBpjsKesehatan: '',
    dokBpjsTenagakerja: '',
    dokSertifikasiDosen: '',
    dokNidn: '',
    imgUrl: '/img/Default-Icon.jpg',
  },
];

type DetailBundle = {
  pegawai: Pegawai;
  kepangkatan: KepangkatanRow[];
  keluarga: AnggotaKeluargaRow[];
  pendidikan: RiwayatPendidikanRow[];
  jafung: JabatanFungsionalRow[];
  inpasing: InpasingRow[];
  jastru: JabatanStrukturalRow[];
  penempatan: PenempatanRow[];
  kendaraan: KendaraanRow[];
};

export const dummyDetail: Record<string, DetailBundle> = {
  '19801231 200501 1 001': {
    pegawai: dummyPegawaiList[0],
    kepangkatan: [
      {
        kepangkatan: 'Penata Muda (III/a)',
        noSK: '820/123/2025',
        tglSK: '01 Juni 2025',
        tmt: '15 Juni 2025',
        tglAkhirKontrak: '14 Juni 2026',
        jenisSK: 'Kenaikan Pangkat',
        gajiPokok: '3.020.000',
        dokumenSK: '/dokumen/sk_pangkat_820-123-2025.pdf',
        mulaiMasaKerja: true,
      },
    ],
    keluarga: [
      {
        nama: 'Siti Aminah',
        tempatLahir: 'Jakarta',
        agama: 'Islam',
        jenisKelamin: 'Perempuan',
        nik: '3174123456789012',
        pendidikan: 'S1',
        hubunganKeluarga: 'Istri',
        tunjanganBeras: '10 kg',
        tunjanganKeluarga: 'Rp 500.000',
        potonganAsuransi: 'Rp 50.000',
        tanggunganPajak: 'Rp 100.000',
      },
    ],
    pendidikan: [
      {
        pendidikan: 'S3 Ilmu Komputer',
        namaInstitusi: 'Institut Teknologi Bandung',
        tahunLulus: '2018',
        dokumen: [
          { namaDokumen: 'Ijazah S3', url: '/dokumen/ijazah_s3.pdf' },
          { namaDokumen: 'Transkrip S3', url: '/dokumen/transkrip_s3.pdf' },
        ],
      },
      {
        pendidikan: 'S2 Ilmu Komputer',
        namaInstitusi: 'Universitas Indonesia',
        tahunLulus: '2012',
        dokumen: [{ namaDokumen: 'Ijazah S2', url: '/dokumen/ijazah_s2.pdf' }],
      },
    ],
    jafung: [
      {
        jabatanFungsional: 'Lektor Kepala',
        noSK: '820/101/2024',
        tglSK: '20 Januari 2024',
        tmt: '01 Februari 2024',
        jenis: 'Penyesuaian Angka Kredit',
        angkaKredit: '200',
        dokumenSK: '/dokumen/sk_jafung_820-101-2024.pdf',
      },
    ],
    inpasing: [
      {
        kepangkatan: 'Penata Muda (III/a)',
        noSK: '123/INP/2023',
        tglSK: '01 April 2023',
        tmt: '15 April 2023',
        dokumenSK: '/dokumen/inpasing_123_INP_2023.pdf',
      },
    ],
    jastru: [
      {
        jabatanStruktural: 'Kepala Laboratorium',
        sk: '123/KPTS/2021',
        periodeMenjabat: '15 Jan 2021 – 14 Jan 2024',
        tunjanganTetap: '2.500.000',
        tunjanganVariable: '500.000',
        dokumenSK: '/dokumen/sk_kalab_123_KPTS_2021.pdf',
      },
    ],
    penempatan: [
      {
        unitKerja: 'Fakultas Teknik',
        noSK: '001/SPT/2025',
        tglSK: '01 Januari 2025',
        tmt: '10 Januari 2025',
        dokumenSK: '/dokumen/penempatan_001_SPT_2025.pdf',
      },
    ],
    kendaraan: [
      {
        namaPemilik: 'Budi Santoso',
        noKendaraan: 'B 1234 XYZ',
        merek: 'Toyota Avanza',
        jenis: 'Mobil',
        dokumen: '/dokumen/ktp_kendaraan_budi.pdf',
      },
    ],
  },
  '19790512 200403 1 002': {
    pegawai: dummyPegawaiList[1],
    kepangkatan: [],
    keluarga: [],
    pendidikan: [],
    jafung: [],
    inpasing: [],
    jastru: [],
    penempatan: [],
    kendaraan: [],
  },
  '19870607 201001 1 003': {
    pegawai: dummyPegawaiList[2],
    kepangkatan: [],
    keluarga: [],
    pendidikan: [],
    jafung: [],
    inpasing: [],
    jastru: [],
    penempatan: [],
    kendaraan: [],
  },
};
